### ISSUE TITLE
Default sorting by updateTs even when the entity does not implement Updateable

### ISSUE THREAD

**Issue by IskandarovRost** [cuba-platform/frontend#120]
1) There is an entity which does not implement Updateable interface
```
@Table(name = "REACTREF_NEW_ENTITY_1")
@Entity(name = "reactref_NewEntity_1")
public class NewEntity_1 extends BaseUuidEntity {
    private static final long serialVersionUID = -1561511052188157401L;

    @Column(name = "SOMEFLD")
    protected String somefld;

    public String getSomefld() {
        return somefld;
    }

    public void setSomefld(String somefld) {
        this.somefld = somefld;
    }
}
```
2) Create front-end components for it: management or cards
3) Start the application
4) Open the screen where the list of entity instances should be displayed

**AR:** It is shown empty and does not work,
```
dataCollection = collection<NewEntity_1>(NewEntity_1.NAME, {
    view: "_local",
    sort: "-updateTs"
  });
```
And exception in CUBA app.log:
```
2020-02-12 21:43:58.299 ERROR [http-nio-8080-exec-4/app-core/user1] com.haulmont.cuba.core.sys.ServiceInterceptor - Exception: 
java.lang.IllegalArgumentException: An exception occurred while creating a query in EntityManager: 
Exception Description: Problem compiling [select e from reactref_NewEntity_1 e order by e.updateTs desc]. 
[46, 56] The state field path 'e.updateTs' cannot be resolved to a valid type.
    at org.eclipse.persistence.internal.jpa.EntityManagerImpl.createQuery(EntityManagerImpl.java:1750) ~[org.eclipse.persistence.jpa-2.7.3-6-cuba.jar:na]
    at com.haulmont.cuba.core.sys.QueryImpl.buildJPAQuery(QueryImpl.java:229) ~[cuba-core-7.2.0.BETA1.jar:7.2.0.BETA1]
    at com.haulmont.cuba.core.sys.QueryImpl.getQuery(QueryImpl.java:138) ~[cuba-core-7.2.0.BETA1.jar:7.2.0.BETA1]
    at com.haulmont.cuba.core.sys.QueryImpl.getResultList(QueryImpl.java:409) ~[cuba-core-7.2.0.BETA1.jar:7.2.0.
```

**Comment by vadimbasko** [comment]
CUBA Studio has issue with project model generated - returns `updatable:false` for all entities.

**Comment by IskandarovRost** [comment]
Reopen. The issue is reproduced for Entity cards component.

1) There is an entity which does not implement Updatable
```
@Table(name = "FETEST5_JUST_ENTITY")
@Entity(name = "fetest5_JustEntity")
public class JustEntity extends BaseUuidEntity {
    private static final long serialVersionUID = 4270515226700939938L;
```
2) Create entity Cards for it
3) Open the copmonent in UI

AR: No cards are displayed
```
@injectMainStore
@observer
export class JstCards extends React.Component<Props> {
  dataCollection = collection<JustEntity>(JustEntity.NAME, {
    view: "_base",
    sort: "-updateTs",
    loadImmediately: false
  });
```
```
Exception Description: Problem compiling [select e from fetest5_JustEntity e order by e.updateTs desc]. 
[44, 54] The state field path 'e.updateTs' cannot be resolved to a valid type.
	at com.haulmont.cuba.core.sys.ServiceInterceptor.aroundInvoke(ServiceInterceptor.java:96) ~[na:na]
```


See also STUDIO-8723

**Comment by IskandarovRost** [comment]
Checked for table and cards. Entity lists and compositions
