### ISSUE TITLE
New Master and List of details could not be persisted together (One_to_many composition)

### ISSUE THREAD

**Issue by IskandarovRost** [cuba-platform/frontend#213]
1) Master is a composition of Details
```

@NamePattern("%s|mastrFld")
@Table(name = "ALPENGOLD_MASTR")
@Entity(name = "alpengold_Mastr")
public class Mastr extends StandardEntity {
    private static final long serialVersionUID = 4663008965573744598L;

    @Column(name = "MASTR_FLD")
    protected String mastrFld;

    @Composition
    @OnDelete(DeletePolicy.CASCADE)
    @OneToMany(mappedBy = "mastr")
    protected List<Dtail> details;

```
2) The views
```
    <view entity="alpengold_Mastr" name="mastr-view" extends="_local">
        <property name="details" view="_local">
            <property name="mastr" view="_minimal"/>
        </property>
    </view>
    <view entity="alpengold_Dtail" name="dtail-view" extends="_local">
        <property name="mastr" view="_minimal"/>
    </view>
```
3) Created components
```
gen-cuba-front react-typescript:entity-management -d ./src/app/mastr -s ../../

? Please select CUBA project you want to use for generation alpengold [/home/rost/StudioProjects/alpengold]

? Entity alpengold_Mastr
? CRUD component class MastrManagement
? List type table
? List component class MastrList
? List view _local

? Edit component class name MastrEdit
? Edit view mastr-view

? View for nested entity attribute details dtail-view

```
4) Start the application
5) Create a new Master and a couple of Details at the same time.
(If to save empty Master and then fill Details - everything is Ok)

**AR:** Error.
![image.png](https://images.zenhubusercontent.com/5aec53f14b5806bc2bd1c28a/b6316ee3-363a-468e-902f-a8c0d92d8649)

This JSON is caught on middleware:
```
{"mastrFld":"1234","details":[{"dtlFld":"1234","mastr":{"id":"new"}}]}
```

This is the exception:
```
19:51:24.357 ERROR c.h.a.r.a.c.RestControllerExceptionHandler- RestAPIException: Cannot deserialize an entity from JSON, 
com.haulmont.cuba.core.app.serialization.EntitySerializationException: java.text.ParseException: Error parsing UUID
	at com.haulmont.cuba.core.app.serialization.EntitySerialization$EntityDeserializer.readEntity(EntitySerialization.java:451) ~[cuba-global-7.2.4.jar:7.2.4]
	at com.haulmont.cuba.core.app.serialization.EntitySerialization$EntityDeserializer.readFields(EntitySerialization.java:566) ~[cuba-global-7.2.4.jar:7.2.4]
	at com.haulmont.cuba.core.app.serialization.EntitySerialization$EntityDeserializer.readEntity(EntitySerialization.java:494) ~[cuba-global-7.2.4.jar:7.2.4]
	at com.haulmont.cuba.core.app.serialization.EntitySerialization$EntityDeserializer.lambda$readCollection$0(EntitySerialization.java:629) ~[cuba-global-7.2.4.jar:7.2.4]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[na:1.8.0_252]
	at com.haulmont.cuba.core.app.serialization.EntitySerialization$EntityDeserializer.readCollection(EntitySerialization.java:628) ~[cuba-global-7.2.4.jar:7.2.4]
	at com.haulmont.cuba.core.app.serialization.EntitySerialization$EntityDeserializer.readFields(EntitySerialization.java:570) ~[cuba-global-7.2.4.jar:7.2.4]
	at com.haulmont.cuba.core.app.serialization.EntitySerialization$EntityDeserializer.readEntity(EntitySerialization.java:494) ~[cuba-global-7.2.4.jar:7.2.4]
	at com.haulmont.cuba.core.app.serialization.EntitySerialization$EntityDeserializer.deserialize(EntitySerialization.java:395) ~[cuba-global-7.2.4.jar:7.2.4]
	at com.haulmont.cuba.core.app.serialization.EntitySerialization$EntityDeserializer.deserialize(EntitySerialization.java:385) ~[cuba-global-7.2.4.jar:7.2.4]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[gson-2.8.6.jar:na]
	at com.google.gson.Gson.fromJson(Gson.java:932) ~[gson-2.8.6.jar:na]
	at com.google.gson.Gson.fromJson(Gson.java:897) ~[gson-2.8.6.jar:na]
	at com.google.gson.Gson.fromJson(Gson.java:846) ~[gson-2.8.6.jar:na]
	at com.google.gson.Gson.fromJson(Gson.java:817) ~[gson-2.8.6.jar:na]
	at com.haulmont.cuba.core.app.serialization.EntitySerialization.entityFromJson(EntitySerialization.java:124) ~[cuba-global-7.2.4.jar:7.2.4]
	at com.haulmont.addon.restapi.api.service.EntitiesControllerManager.createEntityFromJson(EntitiesControllerManager.java:430) ~[restapi-rest-api-7.2.0.jar:na]
	at com.haulmont.addon.restapi.api.service.EntitiesControllerManager.createResponseInfoEntity(EntitiesControllerManager.java:377) ~[restapi-rest-api-7.2.0.jar:na]
	at com.haulmont.addon.restapi.api.service.EntitiesControllerManager.createEntity(EntitiesControllerManager.java:361) ~[restapi-rest-api-7.2.0.jar:na]
	at com.haulmont.addon.restapi.api.controllers.EntitiesController.createEntity(EntitiesController.java:126) ~[restapi-rest-api-7.2.0.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_252]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_252]
	....
Caused by: java.text.ParseException: Error parsing UUID
	at com.haulmont.chile.core.datatypes.impl.UUIDDatatype.parse(UUIDDatatype.java:49) ~[cuba-global-7.2.4.jar:7.2.4]
	at com.haulmont.chile.core.datatypes.impl.UUIDDatatype.parse(UUIDDatatype.java:28) ~[cuba-global-7.2.4.jar:7.2.4]
	at com.haulmont.cuba.core.app.serialization.EntitySerialization$EntityDeserializer.readEntity(EntitySerialization.java:441) ~[cuba-global-7.2.4.jar:7.2.4]
	... 103 common frames omitted

```

**Comment by IskandarovRost** [comment]
If the composition is one_to_one not depending on owning side both entities are persisted OK (no exceptions).

**Comment by IskandarovRost** [comment]
closed
