### ISSUE TITLE
Error on execution "update-model" script from generated front module

### ISSUE THREAD

**Issue by vadimbasko** [cuba-platform/frontend#290]
* Open sample-car-rent in Studio
* Create front module via Studio
* go to generated front module in cli
* exec 'npm run update-model'
* select sample-car-rent project as model source

ER: sdk is updated

AR: project model file searched in incorrect path

```
$ nr update-model

> sample-car-rent@0.1.0 update-model /p/fe/sample-car-rent/modules/front
> gen-cuba-front sdk:all --dest src/cuba

? Please select CUBA project you want to use for generation sample-car-rent [/p/fe/sample-car-rent]
events.js:200
      throw er; // Unhandled 'error' event
      ^

Error: Specified model file does not exist /p/fe/sample-car-rent/modules/front/src/cuba/projectModel.json
    at SdkAllGenerator._readProjectModel (/home/vadim/.nvm/versions/node/v12.14.1/lib/node_modules/@cuba-platform/front-generator/lib/common/base-generator.js:77:19)
    at SdkAllGenerator.<anonymous> (/home/vadim/.nvm/versions/node/v12.14.1/lib/node_modules/@cuba-platform/front-generator/lib/generators/sdk/sdk-generator.js:66:46)

```

**Comment by vadimbasko** [comment]
Not reproduced when call directly `gen-cuba-front sdk:all --dest src/cuba`
