### ISSUE TITLE
Support attributes with attribute type COMPOSITION

### ISSUE THREAD

**Issue by vyacheslav-pushkin** [cuba-platform/frontend#8]
Depends on cuba-platform/restapi#95

### QA Notes

One-to-One Composition attribute will render as a [NestedEntityField](https://doc.cuba-platform.com/frontend/cuba-frontend-docs/v3.0.x/cuba-react-ui/nested-entity-field.html). One-to-Many - as a [NestedEntitiesTableField](https://doc.cuba-platform.com/frontend/cuba-frontend-docs/v3.0.x/cuba-react-ui/nested-entities-table-field.html). Both components will allow editing a nested entity via [EntityEditor](https://doc.cuba-platform.com/frontend/cuba-frontend-docs/v3.0.x/cuba-react-ui/entity-editor.html). Another component that was added as part of this ticket is [ClientSideDataCollectionStore](https://doc.cuba-platform.com/frontend/cuba-frontend-docs/v3.0.x/cuba-react-core/client-side-data-collection-store.html). All these components are available for use on it's own (i.e. outside of the `EntityManagement` template context).

**Comment by IskandarovRost** [comment]
Test-cases(for exploratory testing):
1) One-to-one composition
2) One-to-many composition
3) Check associations
4) Details with undefined instance name
5) Is there Paging in the list of nested Details(on master-edit component)???
6) Which actions are available in the list of (many) details? Try to create, edit, remove. Is There "add" or "exclude"?
7) Master with several composision attributes

**Comment by IskandarovRost** [comment]
Created Studio feature: https://youtrack.haulmont.com/issue/STUDIO-8452 "Compositions attributes when creating Frontend components"

**Comment by IskandarovRost** [comment]
No need to create editor for the nested entity if _local was selected for the edit-component. 

1) There is an entity with composition attribute
2) Create React-typesctipt managment component for it
3) For edit-component view select "_local" or some another view without the link-attribute
**AR:** At the next step the view for the nested entity is asked.
 But *it seems* there is no need in it as it was will not be shown at the screen at all. 

![image.png](https://images.zenhubusercontent.com/5aec53f14b5806bc2bd1c28a/dc45d148-5ac5-4700-994e-bfd04fa14742)

**Comment by IskandarovRost** [comment]
(problem) New Master and List of details could not be persisted together

1) Master is a composition of Details
```

@NamePattern("%s|mastrFld")
@Table(name = "ALPENGOLD_MASTR")
@Entity(name = "alpengold_Mastr")
public class Mastr extends StandardEntity {
    private static final long serialVersionUID = 4663008965573744598L;

    @Column(name = "MASTR_FLD")
    protected String mastrFld;

    @Composition
    @OnDelete(DeletePolicy.CASCADE)
    @OneToMany(mappedBy = "mastr")
    protected List<Dtail> details;

```
2) The views
```
    <view entity="alpengold_Mastr" name="mastr-view" extends="_local">
        <property name="details" view="_local">
            <property name="mastr" view="_minimal"/>
        </property>
    </view>
    <view entity="alpengold_Dtail" name="dtail-view" extends="_local">
        <property name="mastr" view="_minimal"/>
    </view>
```
3) Created components
```
gen-cuba-front react-typescript:entity-management -d ./src/app/mastr -s ../../

? Please select CUBA project you want to use for generation alpengold [/home/rost/StudioProjects/alpengold]

? Entity alpengold_Mastr
? CRUD component class MastrManagement
? List type table
? List component class MastrList
? List view _local

? Edit component class name MastrEdit
? Edit view mastr-view

? View for nested entity attribute details dtail-view

```
4) Start the application
5) Create a new Master and a couple of Details at the same time.
(If to save empty Master and then fill Details - everything is Ok)

**AR:** Error.
![image.png](https://images.zenhubusercontent.com/5aec53f14b5806bc2bd1c28a/b6316ee3-363a-468e-902f-a8c0d92d8649)

This JSON is caught on middleware:
```
{"mastrFld":"1234","details":[{"dtlFld":"1234","mastr":{"id":"new"}}]}
```

This is the exception:
```
19:51:24.357 ERROR c.h.a.r.a.c.RestControllerExceptionHandler- RestAPIException: Cannot deserialize an entity from JSON, 
com.haulmont.cuba.core.app.serialization.EntitySerializationException: java.text.ParseException: Error parsing UUID
	at com.haulmont.cuba.core.app.serialization.EntitySerialization$EntityDeserializer.readEntity(EntitySerialization.java:451) ~[cuba-global-7.2.4.jar:7.2.4]
	at com.haulmont.cuba.core.app.serialization.EntitySerialization$EntityDeserializer.readFields(EntitySerialization.java:566) ~[cuba-global-7.2.4.jar:7.2.4]
	at com.haulmont.cuba.core.app.serialization.EntitySerialization$EntityDeserializer.readEntity(EntitySerialization.java:494) ~[cuba-global-7.2.4.jar:7.2.4]
	at com.haulmont.cuba.core.app.serialization.EntitySerialization$EntityDeserializer.lambda$readCollection$0(EntitySerialization.java:629) ~[cuba-global-7.2.4.jar:7.2.4]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[na:1.8.0_252]
	at com.haulmont.cuba.core.app.serialization.EntitySerialization$EntityDeserializer.readCollection(EntitySerialization.java:628) ~[cuba-global-7.2.4.jar:7.2.4]
	at com.haulmont.cuba.core.app.serialization.EntitySerialization$EntityDeserializer.readFields(EntitySerialization.java:570) ~[cuba-global-7.2.4.jar:7.2.4]
	at com.haulmont.cuba.core.app.serialization.EntitySerialization$EntityDeserializer.readEntity(EntitySerialization.java:494) ~[cuba-global-7.2.4.jar:7.2.4]
	at com.haulmont.cuba.core.app.serialization.EntitySerialization$EntityDeserializer.deserialize(EntitySerialization.java:395) ~[cuba-global-7.2.4.jar:7.2.4]
	at com.haulmont.cuba.core.app.serialization.EntitySerialization$EntityDeserializer.deserialize(EntitySerialization.java:385) ~[cuba-global-7.2.4.jar:7.2.4]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[gson-2.8.6.jar:na]
	at com.google.gson.Gson.fromJson(Gson.java:932) ~[gson-2.8.6.jar:na]
	at com.google.gson.Gson.fromJson(Gson.java:897) ~[gson-2.8.6.jar:na]
	at com.google.gson.Gson.fromJson(Gson.java:846) ~[gson-2.8.6.jar:na]
	at com.google.gson.Gson.fromJson(Gson.java:817) ~[gson-2.8.6.jar:na]
	at com.haulmont.cuba.core.app.serialization.EntitySerialization.entityFromJson(EntitySerialization.java:124) ~[cuba-global-7.2.4.jar:7.2.4]
	at com.haulmont.addon.restapi.api.service.EntitiesControllerManager.createEntityFromJson(EntitiesControllerManager.java:430) ~[restapi-rest-api-7.2.0.jar:na]
	at com.haulmont.addon.restapi.api.service.EntitiesControllerManager.createResponseInfoEntity(EntitiesControllerManager.java:377) ~[restapi-rest-api-7.2.0.jar:na]
	at com.haulmont.addon.restapi.api.service.EntitiesControllerManager.createEntity(EntitiesControllerManager.java:361) ~[restapi-rest-api-7.2.0.jar:na]
	at com.haulmont.addon.restapi.api.controllers.EntitiesController.createEntity(EntitiesController.java:126) ~[restapi-rest-api-7.2.0.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_252]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_252]
	....
Caused by: java.text.ParseException: Error parsing UUID
	at com.haulmont.chile.core.datatypes.impl.UUIDDatatype.parse(UUIDDatatype.java:49) ~[cuba-global-7.2.4.jar:7.2.4]
	at com.haulmont.chile.core.datatypes.impl.UUIDDatatype.parse(UUIDDatatype.java:28) ~[cuba-global-7.2.4.jar:7.2.4]
	at com.haulmont.cuba.core.app.serialization.EntitySerialization$EntityDeserializer.readEntity(EntitySerialization.java:441) ~[cuba-global-7.2.4.jar:7.2.4]
	... 103 common frames omitted

```

**Comment by IskandarovRost** [comment]
(problem) When an entity has severa composition attributes only one of them is presented on edit-component 

1) There is a Master with two Details
```
@NamePattern("%s|mastrFld")
@Table(name = "ALPENGOLD_MASTR")
@Entity(name = "alpengold_Mastr")
public class Mastr extends StandardEntity {
    private static final long serialVersionUID = 4663008965573744598L;

    @Column(name = "MASTR_FLD")
    protected String mastrFld;

    @OneToMany(mappedBy = "mastr")
    @Composition
    @OnDelete(DeletePolicy.CASCADE)
    protected List<DetTwo> twos;

    @Composition
    @OnDelete(DeletePolicy.CASCADE)
    @OneToMany(mappedBy = "mastr")
    protected List<Dtail> details;
```
2) and an apppropriate view 
```
  <view entity="alpengold_Mastr" name="mastr-view" extends="_local">
        <property name="twos" view="_local"/>
        <property name="details" view="_minimal"/>
    </view>
```
3) Created Entity-Management component. See the views for both attributes are asked.
```
gen-cuba-front react-typescript:entity-management -d ./src/app/mastrs -s ../../
? Please select CUBA project you want to use for generation alpengold [/home/rost/StudioProjects/alpengold]
? Entity alpengold_Mastr
? CRUD component class MastrManagement
? List type table
? List component class MastrList
? List view _local

? Edit component class name MastrEdit
? Edit view mastr-view

? View for nested entity attribute twos _local
? View for nested entity attribute details _local

```
4) Start the application

**AR:** only one composition atribute is presented on edit screen. And the second - is not.
![image.png](https://images.zenhubusercontent.com/5aec53f14b5806bc2bd1c28a/68939d3e-50ae-44c8-a8c1-0198f09fbac1)

**Comment by IskandarovRost** [comment]
All the problems and improvements posted to separate issues. Closed.
